### ISSUE TITLE
Add uncertainty calculations

### ISSUE THREAD

**Issue by petebachant** [UNH-CORE/RM2-tow-tank-results-paper#19]
## TODO
- [x] Add sensor info; relevant to #23
- [x] Put error bars on Re dependence plot (UNH-CORE/RM2-tow-tank#95)
- [x] Recalculate uncertainties using standard deviation of the mean
